### ISSUE TITLE
期待，小板凳围观。

### ISSUE THREAD

**Issue by 1c7** [ksco/swift-algorithm-club-cn#1]

**Comment by ksco** [comment]
https://github.com/raywenderlich/swift-algorithm-club

有兴趣吗

**Comment by 1c7** [comment]
有，不过没空，捂脸，有空的时候可能参与吧。
现在在忙一个 Ruby on Rails 项目。

**Comment by 1c7** [comment]
所以你要把那个库进行全部中文化吗？

**Comment by ksco** [comment]
是的，一个月内翻译完，之后保持更新

**Comment by 1c7** [comment]
嗯，滋词~。 哈哈哈。
话说看到原库似乎也是正在完善的样子，Red-Black Tree 没有。

话说我现在 fork 你的库把 big O 那一篇翻译了吧？虽然忙但也没那么夸张的忙

**Comment by ksco** [comment]
欢迎

**Comment by 1c7** [comment]
[挖鼻孔] 搞定一篇你看看吧
